spring:
  main:
    banner-mode: off
    web-application-type: none

  datasource:
    url: 'jdbc:postgresql://${DB_HOST}:${DB_PORT:5432}/${DB_NAME:whales}'
    username: ${DB_USER}
    password: ${DB_PASS}

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
  endpoint:
    health:
      show-details: always
      show-components: always
